### ISSUE TITLE
Crashing in Reaper 6.81/Ubuntu 22.04.3 LTS/Wayland

### ISSUE THREAD

**Issue by maxxatgit** [RafaGago/artv-audio#4]
In Turbo Paco, if I use the down (left) arrow to select the algorithm, and it is currently on "Ambient", Reaper crashes.

If I cycle through clock first,  I can cycle down and it will correctly cycle around to the top.

I tried cycling through bit depth first, but it still crashes.

Awesome plugin! Thanks for supporting Linux.

**Comment by maxxatgit** [comment]
Also in Turbo Paco, the Ambience algorithm doesn't "kick in" or become active when opening a project that already has it selected. I have to select a different algo, then select Ambience, then it becomes active.

**Comment by RafaGago** [comment]
I have been on vacation, so I didn't answer this before.

I have some occurrences likes the one you mention happen to me on the Windows version. I even dedicated some small time (30 min) at some point to try to pinpoint it with no luck.

I develop on Linux and unfortunately on My KDE Neon install (Ubuntu 22.04, X) with Reaper (any version)  I have never been able to reproduce. Browsing works and Ambience is always active when starting even after saving.

If you are a dev yourself, the debug symbols are available on the release artifacts, so a stack trace obtained from a core dump could help. Alternatively the core dump itself, but those are big files.

**Comment by RafaGago** [comment]
Actually now thinking about it I never had crashes on Windows, just that changing the algorithm created peaks and Reaper was muting the channel, which is inconvenient. The thing with not recalling the Ambience preset sounds familiar too.

**Comment by maxxatgit** [comment]
Unfortunately, I'm not a dev. But did start Reaper from the terminal and made it crash. After the crash, this message came up in the terminal:
Floating point exception (core dumped)

Not much. :( 

I'm not sure how to find the core dump text. It usually pops us a few minutes after the crash.

**Comment by RafaGago** [comment]
Interesting. Looks like a division by zero...

To enable core dumps you'd have to do:
> ulimit -S -c unlimited

Then run reaper and reproduce the crash. A file named "core" or "core.<some numbers>" should appear at the local directory. If it's small enough you could probably send it to me (along with the version number of TurboPaco you are using).

If the file is too big then probably you could inspect it with the debugger, but that requires installing gdb and to have the debug symbols for linux uncompressed somwhere. The symbol file for linux is this one if you are using 1.0.2.

https://github.com/RafaGago/artv-audio/releases/download/turbopaco-v1.0.2/turbopaco-linux-v1.0.2-x64-vst3-debug-symbols.zip

So once you have the core file and the symbol file located you would do:

> gdb <path-to-reaper-executable>

Then inside the gdb prompt the symbol files and the core dump have to be loaded.

> symbol-file some-directory/TurboPaco.vst3.syms
> core-file path-to-core-file

After that printing the backtrace.

> bt full

Notice that it might prompt this:

> --Type <RET> for more, q to quit, c to continue without paging--

Press "c" without paging. There is a lot of info. "Ctrl +D" quits "gdb".

Hopefully that information can give some leads. It might also happen that for fixing this I'd have to be able to reproduce, which I'm not.

**Comment by maxxatgit** [comment]
This is strange, I'm not able to generate a core file.  I followed your instructions and looked in the current (home) directory, and also /opt and /opt/REAPER where the reaper binary resides. no file named core or core.

**Comment by RafaGago** [comment]
If you start reaper from the terminal the core file should appear on the directory your prompt is (after crashing):

> ulimit -S -c unlimited
> ~/.local/bin/reaper
> ls -al core*

Notice that my reaper exactuable is there in "~/.local", yours might be in "/opt/something..."

**Comment by maxxatgit** [comment]
$ ls -al core*
ls: cannot access 'core*': No such file or directory

**Comment by RafaGago** [comment]
Well, probably I did something on my machine long ago and forgot. On my machine I get the core file pattern just pointing to the local folder:
> $ cat /proc/sys/kernel/core_pattern
> core

This should be relatively easy to diagnose with generic info and some trial and error:
https://www.google.com/search?channel=fs&client=ubuntu&q=generate+core+dumps+ubuntu+22.04

**Comment by maxxatgit** [comment]
I got a little more information. I got Reaper to crash while running it in gdb:
gdb reaper -ex run -ex bt

then a bunch of stuff when Reaper initializes, then this:

[Thread 0x7fff711ff640 (LWP 14324) exited]
[Thread 0x7fff709fe640 (LWP 14325) exited]
[Thread 0x7fff727ff640 (LWP 14323) exited]
[Thread 0x7fff73bff640 (LWP 14321) exited]
[Thread 0x7fff733fe640 (LWP 14322) exited]
[Thread 0x7fff89dff640 (LWP 14320) exited]
[Thread 0x7fff9efff640 (LWP 14317) exited]
[Thread 0x7fff9e7fe640 (LWP 14318) exited]
[Thread 0x7fff8b26b640 (LWP 14319) exited]
[New Thread 0x7fff8b26b640 (LWP 14428)]
[New Thread 0x7fff9e7fe640 (LWP 14429)]
[Thread 0x7fff8b26b640 (LWP 14428) exited]

Thread 25 "reaper/audio" received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fffe6ffe640 (LWP 14299)]
0x00007fffd00dba2b in ?? () from /home/songsmith/.vst3/TurboPaco.vst3/Contents/x86_64-linux/TurboPaco.so
#0  0x00007fffd00dba2b in  () at /home/songsmith/.vst3/TurboPaco.vst3/Contents/x86_64-linux/TurboPaco.so
#1  0x00007fffd0108ffb in  () at /home/songsmith/.vst3/TurboPaco.vst3/Contents/x86_64-linux/TurboPaco.so
#2  0x00007fffd00d3bf4 in  () at /home/songsmith/.vst3/TurboPaco.vst3/Contents/x86_64-linux/TurboPaco.so
#3  0x00007fffd00c40f7 in  () at /home/songsmith/.vst3/TurboPaco.vst3/Contents/x86_64-linux/TurboPaco.so
#4  0x00000000009a0e3e in  ()
#5  0x0000000000980f81 in  ()
#6  0x00000000007c26c4 in  ()
#7  0x0000000000797d6e in  ()
#8  0x000000000079c7b3 in  ()
#9  0x000000000072740f in  ()
#10 0x000000000072cfc5 in  ()
#11 0x0000000000725c45 in  ()
#12 0x00000000008bc4e9 in  ()
#13 0x00000000008c0f28 in  ()
#14 0x00000000008c3ddf in  ()
#15 0x000000000041ab56 in  ()
#16 0x000000000041f20e in  ()
#17 0x00007ffff740be2b in  () at /opt/REAPER/libSwell.so
#18 0x00007ffff7894b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#19 0x00007ffff7926a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) 

Hope this helps!

**Comment by RafaGago** [comment]
Unfortunately this is missing the debug symbols.The backtrace is just showing stack addresses instead of function names and code lines. That command is missing the debug symbol load. The debug symbol file is the file that enables being able to see function names and code lines.

This might work:
| gdb reaper -ex "symbol-file <some-directory>/TurboPaco.vst3.syms" -ex run
